# -*- coding: utf-8 -*-
"""Generate a 90s theme bed for every Genre Machine genre (v2 prompts).

Two-field ACE-Step conditioning:
  tags   = style & instrumentation (box 1)
  lyrics = structural score - timed section cues and wordless vocal
           textures (box 2). ACE-Step follows the shape loosely, not
           the clock exactly.

Queues jobs on local ComfyUI (127.0.0.1:8188) one at a time, saving
MP3s as genre_machine_mp3_v2/music_<id>_<slug>. Skips ids already
rendered in that folder, so the batch is resumable.
"""
import json
import os
import random
import time
import urllib.request

API = "http://127.0.0.1:8188"
OUT = os.path.expandvars(
    r"%LOCALAPPDATA%\Comfy-Desktop\ComfyUI-Installs\ComfyUI\ComfyUI"
    r"\output\genre_machine_mp3_v2")
SECONDS = 90

def L(*lines):
    return "\n".join(lines)

GENRES = {
"01": ("original",
    "regal brass fanfare intro, majestic orchestral horns, transitioning to a whimsical magical forest theme, sweeping celtic harps, ethereal glockenspiel melody, dreamlike ambiance, cinematic woodwinds, storytelling pace, 80 BPM",
    L("[0:00 - Intro: A proud, regal horn fanfare sounds, establishing a royal storybook beginning]",
      "[0:15 - Horns fade smoothly as sweeping celtic harps roll in, shifting deep into a whimsical forest]",
      "(Vocal texture: Wordless angelic humming, soft floating melody with atmospheric chanting using prolonged Ah and Oh vowel sounds with heavy reverb, no words)",
      "[0:30 - Glockenspiel takes over the main melody, twinkling like fireflies over the steady humming backdrop]",
      "[1:15 - Outro: Instrumentation thins out, leaving only a final trailing harp pluck and a fading vocal echo]")),
"02": ("noir",
    "1940s vintage film noir soundtrack, classic hard-boiled detective theme, melancholic solo tenor saxophone melody, weeping muted trumpet swells, slow brushed snare drums, smoky jazz lounge ambiance, rain sound effects layered, dramatic cinematic tension, instrumental, 65 BPM",
    L("[0:00 - Intro: Heavy patter of city rain fades in, accompanied by a slow, methodical brushed snare drum pattern]",
      "[0:15 - A dark, walking double-bass line enters, creating a low, moody rhythmic pulse]",
      "[0:30 - A smoky, weeping solo saxophone takes over the main melody, sliding through bluesy, late-night jazz scales]",
      "[1:20 - Outro: Instrumentation slowly falls away, leaving only a lingering saxophone note that bleeds into the falling rain]")),
"03": ("cosmic-horror",
    "unsettling cosmic horror ambiance, deep sub-bass drones, eerie detached synthesizer swells, microtonal strings, slow shifting metallic textures, cold lovecraftian space void atmosphere, unearthly tension, 60 BPM",
    L("[0:00 - Intro: A crushing, low-frequency sub-bass drone materializes, filling the room with heavy structural dread]",
      "[0:20 - Eerie, detached synthesizer swells drift in out of tune, sounding cold and mechanical]",
      "(Vocal texture: Distant, overlapping wordless multi-tonal choir chanting, like an ancient non-human language of elongated vowel hums wrapped in heavy hall reverb)",
      "[0:50 - Microtonal strings begin to bend and slide upward, creating immense psychological discomfort]",
      "[1:15 - Outro: The instrumentation dissolves into cold, empty static and a slowly dying low-frequency pulse]")),
"04": ("gothic",
    "dark gothic horror soundtrack, haunting pipe organ chords, weeping classical cello solo, cold harpsichord arpeggios, distant rolling thunder sound effects, shadowy haunted cathedral atmosphere, 70 BPM",
    L("[0:00 - Intro: A massive, distant crack of thunder echoes, followed instantly by deep, somber pipe organ chords]",
      "[0:15 - The organ recedes as a solitary, weeping cello begins a sorrowful classical melody]",
      "(Vocal texture: Haunting Gregorian-style operatic solo vocalise, a mournful wordless lament using dark Om and Uh tones ringing through empty stone halls)",
      "[0:45 - Intricate, icy harpsichord arpeggios weave through the cello melody, increasing the gothic drama]",
      "[1:20 - Outro: The cello holds a final, long, trembling low note as the distant rain fades to black]")),
"05": ("steampunk",
    "neoclassical steampunk orchestration, ticking clockwork percussion, rhythmic gear-grinding sound effects, lively industrial violin pizzicato, driving accordion counter-melody, brass gears, clockwork engine rhythm, instrumental, 95 BPM",
    L("[0:00 - Intro: The crisp, layered sound of complex clockwork gears and swinging pendulums sets a strict, rapid tempo]",
      "[0:15 - A rhythmic, bouncy violin pizzicato pattern joins the clockwork, mimicking a mechanical assembly line]",
      "[0:35 - A rich, driving accordion melody enters, adding vintage European industrial flair]",
      "[1:00 - Steam hiss sound effects interrupt as a punchy, staccato brass section delivers a confident climax]",
      "[1:25 - Outro: The melodic instruments stop abruptly, leaving only a winding pocket watch slowing down]")),
"06": ("cyberpunk",
    "gritty cyberpunk electronic score, pulsing analogue synthwave bassline, aggressive cybernetic drum machine beats, neon retro-futurism, industrial techno synth stabs, dark dystopian city soundtrack, instrumental, 110 BPM",
    L("[0:00 - Intro: A heavy, distorted analogue synthesizer bassline pulses rapidly, painting a neon-lit rain-slicked metropolis]",
      "[0:15 - A sharp, synthetic drum machine beat kicks in with heavy kick drums and crisp electronic claps]",
      "[0:40 - Aggressive, distorted industrial synth stabs slice through the rhythm, mimicking neon lights flashing in the dark]",
      "[1:10 - Outro: The drums cut out completely, leaving the pulsing synth bassline to slowly filter out into digital distortion]")),
"07": ("space-opera",
    "sweeping space opera orchestration, majestic cinematic horn sections, epic ethereal synth pads, soaring starship adventure theme, orchestral strings, cosmic wonder, grand storytelling pace, 85 BPM",
    L("[0:00 - Intro: A vast, expansive synthesizer pad opens up, evoking the infinite silent wonder of a deep star field]",
      "[0:15 - A majestic, soaring orchestral horn melody rises gracefully, a grand starship emerging from warp]",
      "(Vocal texture: Ultra-smooth, ethereal sci-fi soprano vocalise blends with the synths, a wordless floating cosmic hum, zero words)",
      "[0:50 - Rich orchestral violin strings join the horns, building a grand, triumphant crescendo of galactic adventure]",
      "[1:25 - Outro: The orchestration pulls back, leaving only the drifting, peaceful cosmic synth pad to fade into space]")),
"08": ("western",
    "classic spaghetti western soundtrack, lonely whistling melody, twangy electric guitar with heavy tremolo, trotting acoustic guitar percussion, distant coyote howling sound effects, desolate desert outlaw vibe, instrumental, 75 BPM",
    L("[0:00 - Intro: A desolate desert wind blows, followed by a lonely, echo-drenched whistling melody setting a tense showdown mood]",
      "[0:15 - A crisp, trotting acoustic guitar strum establishes a slow horse-riding rhythm under the whistling]",
      "[0:35 - A sharp, iconic electric guitar line with heavy vintage tremolo cuts through, sounding dangerous]",
      "[1:05 - Distant whip-crack and coyote sound effects emphasize the landscape as a dramatic trumpet hits a high peak]",
      "[1:30 - Outro: The instruments fade, leaving only the crackle of a desert bush blowing away in the wind]")),
"09": ("post-apocalyptic",
    "bleak post-apocalyptic soundscape, rusted acoustic guitar picking, cold hollow wind ambient drones, sparse industrial clangs, metallic percussion, desolate wasteland atmosphere, slow pace, 60 BPM",
    L("[0:00 - Intro: A cold, hollow wind sweeps across the stereo field, accompanied by a distant, heavy metallic clang]",
      "[0:15 - A fragile, rusted acoustic guitar begins a slow, sparse, echoing fingerpicked melody in a minor key]",
      "(Vocal texture: A faint, weary, low-pitched wordless male hum breathes underneath, tired and isolated, deep in reverb)",
      "[0:45 - Strange, scraping bowed string textures slide into the background, raising the tension of a hostile wasteland]",
      "[1:20 - Outro: The guitar picking slows to a stop, leaving only the empty, endless wind]")),
"10": ("dystopian",
    "dark dystopian industrial theme, oppressive buzzing synth drones, cold metallic sheet percussion, mechanical rhythmic pulse, tense electronic soundscape, gritty authoritarian atmosphere, instrumental, 80 BPM",
    L("[0:00 - Intro: An oppressive, low-pitched buzzing synthesizer drone enters, establishing an unyielding totalitarian world]",
      "[0:15 - A cold, mechanical drum pulse begins, hitting with the unyielding rhythm of an automated factory line]",
      "[0:40 - Piercing, high-pitched electronic alarm synths swell subtly in the distance, an undercurrent of constant surveillance]",
      "[1:15 - Outro: The mechanical drums cease, leaving the stark industrial hum to slowly lose power and go dark]")),
"11": ("solarpunk",
    "optimistic solarpunk electronic ambiance, warm acoustic marimba patterns, bright uplifting synth plucks, ambient wind chime accents, clean organic grooves, eco-futuristic sunny atmosphere, 90 BPM",
    L("[0:00 - Intro: Crisp, wooden marimba notes ripple gently, mimicking trickling water and sunlight filtering through leaves]",
      "[0:15 - A warm, bouncy organic percussion loop enters, providing a hopeful, productive rhythm that feels alive]",
      "(Vocal texture: Bright, joyful, multi-layered wordless humming harmonies float on top, communal and sunny, zero lyrics)",
      "[0:45 - Glistening synth plucks intertwine with the marimba, a bright picture of clean, harmonious technology]",
      "[1:20 - Outro: The rhythm gently settles, leaving only wind chimes spinning softly in a midday breeze]")),
"12": ("high-fantasy",
    "grand high fantasy orchestration, soaring orchestral flutes, majestic sweeping violins, deep pounding elven war drums, ancient acoustic lutes, legendary adventurous kingdom theme, 85 BPM",
    L("[0:00 - Intro: A solo, ancient-sounding wooden flute plays a soaring melody that evokes green valleys and high castles]",
      "[0:15 - Deep, resonant orchestral war drums strike a slow, proud rhythm, with the gentle strumming of an acoustic lute]",
      "(Vocal texture: A grand, soaring elven-style wordless choir joins, chanting open, epic vowel sounds, ancient and mythical)",
      "[0:50 - Sweeping orchestral violins join the melody, driving into a breathtaking, emotional high fantasy crescendo]",
      "[1:25 - Outro: The heavy drums stop, leaving the lone flute to play a final, peaceful cadence echoing into the hills]")),
"13": ("anime",
    "high-energy anime orchestral pop, sparkling digital piano melodies, soaring emotional string arrangements, driving energetic bass guitar, upbeat j-rock drum rhythms, vibrant colorful instrumental, 130 BPM",
    L("[0:00 - Intro: A rapid, sparkling digital piano run explodes into the arrangement, bursting with youthful energy]",
      "[0:15 - Driving, hyper-clean rock drums and a bouncy bass guitar line kick in, establishing a fast, exciting pace]",
      "[0:35 - Soaring, emotional orchestral strings sweep across the melody, adding dramatic cinematic weight]",
      "[1:10 - Outro: A rapid drum roll leads into a final, ringing piano chord that sustains and sparkles before fading]")),
"14": ("superhero",
    "epic superhero comic theme, bold punchy brass sections, driving cinematic orchestral staccato strings, heroic snare drum rolls, soaring orchestral brass, action-packed blockbuster pace, instrumental, 100 BPM",
    L("[0:00 - Intro: A fast, driving staccato string pattern builds intense, heroic anticipation like a comic page-turn]",
      "[0:15 - Bold, punchy orchestral horns burst in with a definitive, soaring heroic motif, radiating confidence]",
      "[0:40 - Crisp snare drum rolls and crashing cymbals elevate the rhythm, a fast-paced cityscape action sequence]",
      "[1:15 - Outro: A massive final orchestral brass chord hits hard on the downbeat, sustaining majestically before cutting off]")),
"15": ("silent-film",
    "1920s vintage silent film ragtime piano, upbeat honky-tonk piano melody, flickering projector sound effects, old lo-fi vinyl crackle, fast-paced slapstick piano chord progressions, nostalgic instrumental, 115 BPM",
    L("[0:00 - Intro: The flicker of a 1920s film projector and heavy vinyl crackle, followed by a solo piano flourish]",
      "[0:10 - A fast-paced, highly animated honky-tonk ragtime piano melody takes off, full of frantic theatrical energy]",
      "[0:40 - The piano shifts to a minor, exaggerated villain-theme progression for a moment, creating comical suspense]",
      "[1:05 - The playful, bouncy main ragtime theme returns slightly faster, building to a dramatic theatrical finish]",
      "[1:25 - Outro: A final, loud comedic piano chord stabs down, followed by the lonely whirring of the projector fading]")),
"16": ("suburban-mystery",
    "eerie 1950s suburban mystery theme, warbling vintage theremin melody, plucked orchestral strings, muted jazz vibraphone chords, pristine white-picket-fence suspense atmosphere, retro instrumental, 75 BPM",
    L("[0:00 - Intro: A warbling, spooky vintage theremin melody glides through the air, immediately eerie and unsettling]",
      "[0:15 - Sneaky, plucked staccato violin strings join in, tip-toeing through a pristine manicured neighborhood]",
      "[0:35 - Cool, muted jazz vibraphone chords enter, a smooth but deeply suspicious mid-century lounge layer]",
      "[1:10 - Outro: The plucked strings slow to a standstill, leaving the theremin to slide up to a final, questioning high note]")),
"17": ("cold-war-spy",
    "tense cold war spy thriller theme, stealthy low cimbalom plucking, muted staccato brass accents, ticking spy watch percussion, cold soviet-era concrete ambiance, high-stakes suspense, instrumental, 80 BPM",
    L("[0:00 - Intro: A sharp, metallic cimbalom picks a stealthy, repeating pattern, evoking late-night espionage]",
      "[0:15 - An ultra-quiet, ticking percussion pattern begins, a hidden spy watch counting down seconds]",
      "[0:35 - Cold, muted staccato brass hits slice through the shadows, sharp spikes of high-stakes suspense]",
      "[1:10 - Outro: The brass cuts out, leaving only the stealthy cimbalom pattern to fade into the dark winter night]")),
"18": ("true-crime",
    "modern true crime documentary score, cold repetitive felt piano keys, pulsing minimalist synth bass, sparse industrial clock textures, dark brooding investigation atmosphere, instrumental, 70 BPM",
    L("[0:00 - Intro: A single, deeply muted felt piano key repeats a slow, cold, hypnotic note, dripping with mystery]",
      "[0:15 - A low, warm, pulsing minimalist synthesizer bassline enters, an undercurrent of serious investigation]",
      "[0:40 - Sparse, mechanical ticking textures click in the background, a clock in an interrogation room]",
      "[1:15 - Outro: The bassline disappears, leaving the cold, single piano key to repeat until it falls silent]")),
"19": ("courtroom",
    "serious courtroom drama score, intense staccato orchestral strings, driving classical cello ostinato, rolling timpani drums, sharp gavel strike accents, high-stakes legal tension, instrumental, 75 BPM",
    L("[0:00 - Intro: A sharp percussion hit like a courtroom gavel, immediately followed by tense staccato violins]",
      "[0:15 - A driving, serious cello ostinato locks in, building an atmosphere of cross-examination]",
      "[0:40 - Low, rolling timpani drums rumble underneath, escalating the stakes as arguments reach a peak]",
      "[1:20 - Outro: The staccato strings freeze on a sharp, unresolved chord, hanging in mid-air before cutting away]")),
"20": ("romance",
    "sweeping cinematic romance theme, beautiful warm solo grand piano melody, lush emotional string orchestra, soft concert harp glissandos, tender passionate storytelling ambiance, instrumental, 65 BPM",
    L("[0:00 - Intro: A beautiful, warm solo grand piano begins a tender, elegant melody with soft expressive timing]",
      "[0:15 - Lush, warm orchestral violin strings gently swell underneath the piano, wrapping it in emotional depth]",
      "(Vocal texture: A breathy, angelic wordless female vocalise hums a comforting counter-melody with deep reverb)",
      "[0:50 - A soft concert harp rolls through beautiful glissandos, lifting the arrangement into a sweeping climax]",
      "[1:25 - Outro: The strings slowly fade, leaving the grand piano to play three quiet, peaceful closing notes]")),
"21": ("heist",
    "high-stakes heist jazz soundtrack, stealthy muted walking bassline, rhythmic hi-hat jazz drums, intricate vibraphone lines, sudden sharp horn section stabs, smooth precision robbery theme, instrumental, 105 BPM",
    L("[0:00 - Intro: A stealthy, ultra-crisp jazz hi-hat rhythm starts, followed by a fast, intricate walking double-bass line]",
      "[0:15 - A cool, complex vibraphone melody enters, a team of experts moving with precision through laser grids]",
      "[0:35 - The jazz drums pick up energy, a rolling ride cymbal ratcheting up the ticking-clock tension]",
      "[1:05 - Sudden, sharp staccato brass stabs hit on the downbeats, signaling a dramatic escape sequence]",
      "[1:30 - Outro: A final, tight drum fill stops instantly on a single bass note, total slick precision]")),
"22": ("detective",
    "classic detective mystery score, curious pizzicato string plucking, sneaky woodwind melodies, low inquisitive bassoon lines, quiet ticking percussion, foggy london street atmosphere, instrumental, 70 BPM",
    L("[0:00 - Intro: Curious, playful pizzicato violin strings pluck a sneaky, inquisitive pattern, classic mystery]",
      "[0:15 - A low, warm bassoon and a light flute join in call-and-response, a detective looking for clues]",
      "[0:40 - A light, metallic ticking percussion texture enters, keeping a cautious pace through the fog]",
      "[1:15 - Outro: The woodwinds trail off into a questioning cadence, a final soft string pluck closing the file]")),
"23": ("survival",
    "raw wilderness survival score, primal acoustic wooden flutes, organic hand drum percussion, scraping cello textures, gritty survivalist tension, vast wild nature landscape theme, 75 BPM",
    L("[0:00 - Intro: A raw, primitive wooden flute echoes over empty sonic space, lonely, ancient, and wild]",
      "[0:15 - Deep, organic hand drums and wooden shakers begin a slow, grounding rhythm, walking through deep snow]",
      "(Vocal texture: A deep, gravelly, wordless throat-humming texture from below, a fierce primal survival element)",
      "[0:45 - Gritty, harshly scraped cello strings enter, adding physical danger, cold weather, wild predators]",
      "[1:20 - Outro: The drums stop, leaving the primal flute to exhale one final, long air-filled note into the wilderness]")),
"24": ("slapstick",
    "frantic 1940s slapstick cartoon score, bouncy xylophone melodies, slide whistle sound effects, boisterous muted trumpets, spring-boing percussion, chaotic funny cartoon pace, instrumental, 120 BPM",
    L("[0:00 - Intro: A chaotic, rapid xylophone run bursts forward, followed by an iconic, funny slide-whistle]",
      "[0:12 - Boisterous, laughing muted trumpets play a bouncy, ridiculous melody, a character running at top speed]",
      "[0:35 - Sudden percussion effects crash in: comical spring-boings, cowbells, and frying-pan metallic dings]",
      "[1:10 - Outro: A rapid, frantic orchestral crescendo builds, ending in a massive bass drum thud and a dizzy slide whistle]")),
"25": ("mythic-epic",
    "colossal mythic epic orchestration, thunderous orchestral taiko drums, roaring cinematic horn walls, sweeping mythological strings, ancient legendary battle theme, 80 BPM",
    L("[0:00 - Intro: Earth-shattering taiko war drum strikes shake the soundscape, establishing legendary, mythic scale]",
      "[0:15 - A roaring, titanic wall of orchestral horns rises, an ancient melody fit for gods and heroes]",
      "(Vocal texture: A massive, powerful wordless operatic choir bellows thunderous, dramatic vowel chords in unison)",
      "[0:50 - Full string sections surge forward in fast staccato waves, driving an epic, sweeping battle climax]",
      "[1:30 - Outro: A final monumental cymbal crash and a deep, sustaining low horn blast rumble out into silence]")),
"26": ("science-fiction",
    "futuristic science fiction score, vintage analog synthesizer arpeggios, pulsing electronic sub-bass, alien theremin melodies, sleek starship laboratory atmosphere, high-tech instrumental, 90 BPM",
    L("[0:00 - Intro: A complex, cascading vintage analog synthesizer arpeggio ripples through space, high-tech and alien]",
      "[0:15 - A deep, ultra-clean pulsing electronic sub-bass kicks in, smooth rhythmic drive like a starship engine core]",
      "(Vocal texture: A smooth, synthesized vocoder-style wordless robotic hum glides through chords in the background)",
      "[0:45 - Gleaming, sweeping synth leads take center stage, soaring across a neon-lit sci-fi landscape]",
      "[1:20 - Outro: Drums and bass drop out, leaving the glittering synth arpeggio to echo away into deep space]")),
"27": ("action-adventure",
    "high-octane action adventure score, fast-paced staccato strings, driving cinematic percussion loops, punchy heroic brass stabs, adrenaline-fueled chase theme, instrumental, 115 BPM",
    L("[0:00 - Intro: An explosive, fast-paced orchestral percussion loop bursts in, locking an adrenaline-pumping tempo]",
      "[0:15 - Razor-sharp staccato violins start a relentless driving pattern, an intense chase sequence]",
      "[0:35 - Punchy, aggressive heroic brass stabs through the rhythm, lifting the action to blockbuster scale]",
      "[1:15 - Outro: A rapid-fire drum roll rolls into a massive, abrupt orchestral hit that stops the track on a dime]")),
"28": ("ghost-horror",
    "eerie supernatural horror soundtrack, detuned nursery rhyme music box melody, creeping cold ambient string pads, ghostly haunting atmosphere, instrumental, 65 BPM",
    L("[0:00 - Intro: A chilling, slightly detuned vintage music box slowly plays a broken nursery rhyme in an empty room]",
      "[0:18 - A cold, creeping ambient string pad rises from underneath, suffocating the music box in supernatural dread]",
      "(Vocal texture: A ghostly, disembodied wordless female whisper-hum breathes past the microphone with unsettling stereo panning)",
      "[0:45 - The strings swell upward in a slow, rising surge of dread that crests and recedes without breaking]",
      "[1:20 - Outro: The music box completely winds down and stops, leaving a faint, freezing ambient drone to fade]")),
"29": ("biography",
    "reflective biography score, nostalgic warm acoustic piano chords, gentle emotional violin solo, soft acoustic guitar picking, intimate personal storytelling ambiance, instrumental, 70 BPM",
    L("[0:00 - Intro: A reflective, deeply personal acoustic piano begins a gentle, nostalgic chord progression]",
      "[0:15 - A soft, warm acoustic guitar begins a sparse fingerpicked pattern alongside, an intimate diary feel]",
      "[0:35 - A single, beautifully expressive solo violin takes the melody, a wave of rich, bittersweet memory]",
      "[1:15 - Outro: The violin gently rests, leaving the piano to carry a final, peaceful chord that settles with grace]")),
"30": ("historical-fiction",
    "majestic historical fiction orchestration, authentic acoustic period instrumentation, sweeping classical string sections, regal woodwinds, grand ancient castle court theme, 75 BPM",
    L("[0:00 - Intro: An authentic period lute and classical harp set a stately, regal royal tempo]",
      "[0:15 - Elegant, sweeping classical strings join, painting a grand historical palace court]",
      "(Vocal texture: A formal, clean, wordless classical chamber choir provides smooth harmonic beds underneath)",
      "[0:45 - Regal wooden flutes and oboes lift the melody, a dignified, emotionally rich historical theme]",
      "[1:25 - Outro: The orchestra backs away, allowing the solo period string instrument a final, formal royal cadence]")),
"31": ("stage-drama",
    "intimate stage drama score, minimal melancholy felt piano, solo expressive cello, quiet theatrical room tone ambiance, intense emotional dialogue backing, instrumental, 65 BPM",
    L("[0:00 - Intro: A minimal, melancholy felt piano plays slow, spaced-out chords, leaving immense breathing room]",
      "[0:15 - An incredibly expressive solo cello joins, sliding through long, sorrowful notes of immense weight]",
      "[0:40 - The arrangement stays strictly minimalist and quiet, designed to sit entirely underneath a spoken voice]",
      "[1:15 - Outro: The cello holds its final note with slow vibrato as the piano plays one last, deep unresolved key]")),
"32": ("graphic-novel",
    "edgy graphic novel theme, dark modern industrial trip-hop beat, gritty distorted bass guitar riffs, smoky vinyl scratch textures, urban comic noir aesthetic, instrumental, 85 BPM",
    L("[0:00 - Intro: A gritty, heavy trip-hop drum beat kicks in with dusty vinyl crackle, modern urban comic style]",
      "[0:15 - A dark, heavily distorted bass guitar riff rolls in, sharp edgy rock attitude under the hip-hop rhythm]",
      "[0:40 - Ghostly, smoky jazz horn swells are chopped and sampled in the background, deeply stylized]",
      "[1:15 - Outro: The drums stop, leaving the gritty distorted bass loop to filter out into heavy vinyl crackle]")),
"33": ("ergodic",
    "avant-garde experimental soundscape, unpredictable non-linear time signatures, abstract prepared piano plucks, erratic typewriter clicks, tape loops, strange ambient glitch textures, academic avant-garde instrumental, 80 BPM",
    L("[0:00 - Intro: A highly unpredictable, abstract pattern of plucked internal piano strings and erratic typewriter clicks begins]",
      "[0:15 - The rhythm deliberately shifts time signatures erratically, a fascinating non-linear experimental maze]",
      "[0:40 - Eerie tape loops, abstract glitch textures, and reversed instrumental sounds warp between the speakers]",
      "[1:20 - Outro: The chaotic elements suddenly collapse into a single, sharp clockwork mechanical snap that cuts all audio]")),
"34": ("transgressive",
    "raw transgressive punk instrumentation, aggressive distorted electric guitar garage riffs, driving fast messy rock drums, heavy industrial bass fuzz, chaotic counter-culture energy, instrumental, 140 BPM",
    L("[0:00 - Intro: A wall of raw, heavily distorted electric guitar feedback screams out, bursting with aggression]",
      "[0:10 - Fast, messy, unpolished garage-rock drums slam in, driving a relentless, rebellious tempo]",
      "[0:35 - The bass guitar, drenched in heavy fuzz, locks into the riffs, raising the chaotic punk energy to a peak]",
      "[1:15 - Outro: The drums dissolve into a wild, frantic cymbal smash as the guitar amplifier hums with raw feedback]")),
"35": ("climate-fiction",
    "sweeping climate fiction soundscape, beautiful melting glass ambient synths, solemn acoustic woodwinds, rolling ocean wave sound effects, fragile environmental beauty theme, 70 BPM",
    L("[0:00 - Intro: The soothing, deep sound of rolling ocean waves and distant cracking ice cascades into a vast, empty space]",
      "[0:15 - Beautiful, crystal-clear glass synthesizer pads melt and shift slowly, a fragile planetary scale]",
      "(Vocal texture: A mournful, single wordless soprano voice hums a long, echoing lament for nature, in heavy shimmer reverb)",
      "[0:45 - A solemn wooden flute enters, playing a simple, heartbreaking melody over the ocean and synths]",
      "[1:25 - Outro: The music completely fades, leaving only the natural sound of running water and wind]")),
"36": ("slipstream",
    "surreal slipstream music, dream-pop electric guitars with heavy chorus, swirling ethereal synthesizers, floating jazz fusion rhythms, blurring reality boundaries theme, 88 BPM",
    L("[0:00 - Intro: Swirling dream-pop electric guitars dripping in vintage chorus and delay melt the listener into a trance]",
      "[0:15 - A light, floating jazz-fusion drum rhythm begins, weightless, moving through a fluid dreamscape]",
      "(Vocal texture: Ethereal, layered wordless vocal textures swirl across the ceiling, washing over the guitars)",
      "[0:45 - The synth pads shift keys unexpectedly, a beautifully strange feeling of reality slipping and blurring]",
      "[1:20 - Outro: The drums melt away, leaving shimmering guitar chords to echo and dissolve into silence]")),
"37": ("bangsian",
    "mystical bangsian afterlife score, celestial pipe organ, shimmering angelic harps, echoing limestone underworld cavern reverb, baroque classical instrumentation, 65 BPM",
    L("[0:00 - Intro: A celestial, shimmering harp glissando echoes inside a massive, infinite limestone cavern]",
      "[0:15 - Deep, majestic but distant baroque pipe organ chords rise, a grand mythical hall of the afterlife]",
      "(Vocal texture: A beautiful, haunting classical wordless choir sings hollow, echoing Ah vowels from deep in the background)",
      "[0:50 - Classical strings join the organ, building a majestic, bittersweet, timeless mythological peak]",
      "[1:25 - Outro: The orchestration thins, leaving a single, echoing harp note to chime in the dark cavern hall]")),
"38": ("black-comedy",
    "quirky black comedy score, jaunty pizzicato cello plucking, ironic cheerful whistling, macabre bassoon melodies, dry comedic tango percussion, dark humor instrumental, 90 BPM",
    L("[0:00 - Intro: A jaunty, highly ironic pizzicato cello plucks a bouncy, cheerful rhythm that feels deeply sarcastic]",
      "[0:15 - A dry, comically dark tango percussion beat enters, driven by a low, mischief-filled bassoon melody]",
      "[0:35 - An ironic, cheerful whistling melody joins, a funny, stark contrast against the macabre tone]",
      "[1:10 - Outro: The music abruptly stumbles to a halt mid-phrase, ending on a single deadpan pizzicato pluck]")),
"39": ("magical-realism",
    "whimsical magical realism score, sparkling warm acoustic piano runs, sudden surreal accordion swells, twinkling acoustic chimes, soft marimba accents, blending ordinary life with magic vibe, instrumental, 80 BPM",
    L("[0:00 - Intro: A warm, ordinary acoustic piano plays a simple street melody, which suddenly bursts into a sparkling run]",
      "[0:15 - Twinkling wind chimes, soft marimba, and a sudden surreal accordion swell inject magic into the ordinary rhythm]",
      "(Vocal texture: A warm, comforting wordless female hum skips playfully along with the piano, intimate and cozy)",
      "[0:45 - The piano and accordion blend into a rich, sweeping, dream-like folk waltz, grounded yet floating]",
      "[1:25 - Outro: The accordion settles, leaving the piano one final, simple chord as a wind chime spins to a stop]")),
"40": ("epistolary",
    "intimate epistolary score, scratching fountain pen sound effects, soft emotional felt piano keys, warm acoustic cello background, old hand-written letter nostalgia, instrumental, 60 BPM",
    L("[0:00 - Intro: The crisp, clear sound of a fountain pen scratching across old textured paper, rhythmic and close]",
      "[0:12 - A soft, deeply muted felt piano begins a slow, intimate melody, the reading of an old letter]",
      "[0:35 - A warm, expressive acoustic cello bows long, comforting low notes underneath, thickening the nostalgia]",
      "[1:15 - Outro: The piano slows to a gentle whisper, closing as a paper letter is folded shut]")),
}


def queue(gid, slug, tags, lyrics):
    wf = {
        "1": {"class_type": "CheckpointLoaderSimple",
              "inputs": {"ckpt_name": "ace_step_v1_3.5b.safetensors"}},
        "2": {"class_type": "ModelSamplingSD3", "inputs": {"model": ["1", 0], "shift": 5.0}},
        "3": {"class_type": "EmptyAceStepLatentAudio",
              "inputs": {"seconds": SECONDS, "batch_size": 1}},
        "4": {"class_type": "TextEncodeAceStepAudio",
              "inputs": {"clip": ["1", 1], "tags": tags,
                         "lyrics": lyrics, "lyrics_strength": 0.99}},
        "5": {"class_type": "ConditioningZeroOut", "inputs": {"conditioning": ["4", 0]}},
        "6": {"class_type": "KSampler",
              "inputs": {"model": ["2", 0], "positive": ["4", 0], "negative": ["5", 0],
                         "latent_image": ["3", 0], "seed": random.randint(0, 2**32),
                         "steps": 50, "cfg": 5.0, "sampler_name": "euler",
                         "scheduler": "simple", "denoise": 1.0}},
        "7": {"class_type": "VAEDecodeAudio", "inputs": {"samples": ["6", 0], "vae": ["1", 2]}},
        "8": {"class_type": "SaveAudioMP3",
              "inputs": {"audio": ["7", 0], "quality": "128k",
                         "filename_prefix": "genre_machine_mp3_v2/music_%s_%s" % (gid, slug)}},
    }
    req = urllib.request.Request(API + "/prompt", json.dumps({"prompt": wf}).encode(),
                                 {"Content-Type": "application/json"})
    return json.loads(urllib.request.urlopen(req, timeout=30).read())["prompt_id"]


def wait(pid):
    while True:
        time.sleep(5)
        h = json.loads(urllib.request.urlopen(API + "/history/" + pid, timeout=30).read())
        if pid in h:
            st = h[pid].get("status", {})
            if st.get("completed"):
                return True
            if st.get("status_str") == "error":
                print("  ERROR", json.dumps(st)[:500], flush=True)
                return False


if __name__ == "__main__":
    for gid, (slug, tags, lyrics) in GENRES.items():
        name = "music_%s_%s_00001.mp3" % (gid, slug)
        if os.path.exists(os.path.join(OUT, name)):
            print(gid, slug, "already done, skipping", flush=True)
            continue
        t0 = time.time()
        ok = wait(queue(gid, slug, tags, lyrics))
        print(gid, slug, "ok" if ok else "FAILED", "%.0fs" % (time.time() - t0), flush=True)
    print("batch complete", flush=True)
