"""
Genre Machine - sync markdown scripts back into the site.

The Stories/ markdown files are the place you write and edit. This reads every
"## Script" section that has real prose in it and writes data/scripts-generated.js,
which the page loads after data/stories.js and merges over the top.

data/stories.js is never modified.

Usage (from the project root):
    python tools/sync_scripts.py
"""

import glob
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "data", "scripts-generated.js")

PREFIX_TO_ID = {
    "Three Little Pigs": "pigs",
    "Little Red Riding Hood": "red",
    "Goldilocks and the Three Bears": "goldilocks",
    "Cinderella": "cinderella",
}


def main():
    out = {}
    audio = {}
    for path in glob.glob(os.path.join(ROOT, "Stories", "*", "*.md")):
        raw = open(path, encoding="utf-8").read()
        if not raw.startswith("---"):
            continue
        fm = raw.split("---", 2)[1]

        def field(k):
            m = re.search(r'^%s:\s*"?(.*?)"?\s*$' % k, fm, re.M)
            return m.group(1) if m else ""

        sid = PREFIX_TO_ID.get(field("story"))
        gid = field("genre_id")
        if not sid or not gid:
            continue
        script = raw.split("## Script", 1)[1].split("## Voice design", 1)[0].strip()
        if not script or script.startswith("> [!todo]"):
            continue
        out.setdefault(sid, {})[gid] = script
        if field("audio"):
            audio.setdefault(sid, {})[gid] = field("audio")

    body = [
        "/* GENERATED by tools/sync_scripts.py - do not edit by hand.",
        "   Merges the Stories/*.md scripts over data/stories.js. */",
        "(function () {",
        "  var D = window.GENRE_MACHINE_DATA;",
        "  if (!D) { return; }",
        "  var TEXTS = " + json.dumps(out, ensure_ascii=False, indent=2) + ";",
        "  var AUDIO = " + json.dumps(audio, ensure_ascii=False, indent=2) + ";",
        "  D.stories.forEach(function (s) {",
        "    if (TEXTS[s.id]) { s.texts = Object.assign(s.texts || {}, TEXTS[s.id]); }",
        "    if (AUDIO[s.id]) { s.audio = Object.assign(s.audio || {}, AUDIO[s.id]); }",
        "  });",
        "}());",
        "",
    ]
    open(OUT, "w", encoding="utf-8").write("\n".join(body))
    total = sum(len(v) for v in out.values())
    print("wrote data/scripts-generated.js: %d scripts, %d with audio"
          % (total, sum(len(v) for v in audio.values())))
    for sid, v in sorted(out.items()):
        print("  %-12s %d" % (sid, len(v)))


if __name__ == "__main__":
    main()
